### ISSUE TITLE
Chat 4.2 Inheritance Issue

### ISSUE THREAD

**Issue by amart241** [cisagov/ScubaGoggles#66] opened 2023-12-07 19:00 UTC
If 4.1 is non-compliant, then 4.2 is 'disabled' and it can't be selected. Should we change the baseline to address this?

**Comment by LaurenBassett** [comment] 2024-02-07 19:26
Blocked because waiting on feedback from the TC team. Once it is clear, we can address the setting inheritance. We will revisit after baseline is updated.

**Comment by snarve** [comment] 2024-02-08 04:06
duplicate of #63, closing this issue

**Closed by snarve** 2024-02-08 04:06 UTC
Labels: bug, Baseline Revision, In-progress
